#pragma once
#ifndef VERSION_HPP_NEROSHOP
#define VERSION_HPP_NEROSHOP

#define NEROSHOP_VERSION_CODENAME ""
#define NEROSHOP_VERSION_METADATA "-alpha"
#define NEROSHOP_VERSION_MAJOR "0"
#define NEROSHOP_VERSION_MINOR "1"
#define NEROSHOP_VERSION_PATCH "0"
#define NEROSHOP_VERSION NEROSHOP_VERSION_MAJOR "." NEROSHOP_VERSION_MINOR "." NEROSHOP_VERSION_PATCH NEROSHOP_VERSION_METADATA
#define NEROSHOP_VERSION_FULL "neroshop v" NEROSHOP_VERSION " " NEROSHOP_VERSION_CODENAME
#define NEROSHOP_DAEMON_VERSION NEROSHOP_VERSION
#define NEROSHOP_DHT_VERSION "1.0"//"NS" NEROSHOP_VERSION_MAJOR NEROSHOP_VERSION_MINOR

#endif
