#pragma once
#ifndef NEROSHOP_VERSION_HPP
#define NEROSHOP_VERSION_HPP

#define NEROSHOP_VERSION_CODENAME ""
#define NEROSHOP_VERSION_METADATA "-alpha"
#define NEROSHOP_VERSION_MAJOR "0"
#define NEROSHOP_VERSION_MINOR "1"
#define NEROSHOP_VERSION_PATCH "0"
#define NEROSHOP_VERSION NEROSHOP_VERSION_MAJOR "." NEROSHOP_VERSION_MINOR "." NEROSHOP_VERSION_PATCH
#define NEROSHOP_VERSION_FULL "neroshop v" NEROSHOP_VERSION NEROSHOP_VERSION_METADATA " " NEROSHOP_VERSION_CODENAME

#endif
